### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by tevon456** [orionsearch/SearchKit-JS#1]
will there be more documentation in the readme.md soon?

**Comment by arguiot** [comment]
OrionSearch is a new project, and we're currently building it (and if you're interested, you can help us).

There will definitely be decent and friendly documentation as soon as we finish building it and release the first version.

**Comment by tevon456** [comment]
I'd love to help

**Comment by arguiot** [comment]
Fantastic! Do you plan to contribute through PRs or do you want to join the organization?

**Comment by tevon456** [comment]
I'd like to be a aprt of the organization if thats okay.
  
  
  
  

  
>

**Comment by arguiot** [comment]
Then you can join the following discord server: https://discord.gg/nBbvQm (the link will expire in 1 day)

**Comment by tevon456** [comment]
Thanks im just downloading the app now
  

  
  

  
  
>
